from fpdf import FPDF
import datetime

class AuditPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'ML Model Audit Report', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Generated by ML-Auditor | {datetime.date.today()}', 0, 0, 'C')

def sanitize_text(text):
    """
    Cleans text for FPDF.
    1. Replaces smart quotes.
    2. Removes emojis/non-latin1 characters that cause crash.
    """
    if not text:
        return ""
    
    # 1. Replace smart characters
    replacements = {
        '\u2018': "'", '\u2019': "'",  # Single quotes
        '\u201c': '"', '\u201d': '"',  # Double quotes
        '\u2013': '-', '\u2014': '-',  # Dashes
        '\u2026': '...'               # Ellipsis
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    
    # 2. Remove Emojis and non-Latin-1 characters
    return text.encode('latin-1', 'ignore').decode('latin-1')

def generate_pdf_report(results, output_filename="audit_report.pdf"):
    pdf = AuditPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Title
    pdf.set_font('Arial', 'B', 16)
    file_name = sanitize_text(results.get('file_name', 'Unknown'))
    pdf.cell(0, 10, f"File: {file_name}", 0, 1)
    
    # Score
    pdf.set_font('Arial', '', 12)
    score = results.get('score', 0)
    pdf.cell(0, 10, f"Overall Health Score: {score}/100", 0, 1)
    
    # Status
    if score > 80:
        status = "PASSED"
    elif score > 50:
        status = "NEEDS IMPROVEMENT"
    else:
        status = "CRITICAL FAILURES DETECTED"
    
    pdf.cell(0, 10, f"Status: {status}", 0, 1)
    pdf.ln(10)

    # Issues
    issues = results.get('issues', [])
    if not issues:
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, "No issues found.", 0, 1)
    else:
        for i, issue in enumerate(issues):
            pdf.set_font('Arial', 'B', 12)
            
            issue_type = sanitize_text(issue.get('type', 'Unknown'))
            severity = sanitize_text(issue.get('severity', 'N/A'))
            line = issue.get('line', 'N/A')
            msg = sanitize_text(issue.get('message', ''))
            
            text = f"Issue #{i+1}: {issue_type} [{severity}]"
            pdf.cell(0, 10, text, 0, 1)
            
            pdf.set_font('Arial', '', 10)
            pdf.multi_cell(0, 5, f"Line {line}: {msg}")
            
            if 'llm_explanation' in issue:
                pdf.set_font('Arial', 'I', 10)
                explanation = sanitize_text(issue['llm_explanation'])
                pdf.multi_cell(0, 5, f"AI Insight: {explanation}")
            
            pdf.ln(5)

    pdf.output(output_filename)
    return output_filename